### PR TITLE
since 9.0.1 is done, next freeze versions are...
... only 9.1.*, not 9.*

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by maxandersen** [comment]
I don't follow what this fix is doing/fixing ? 

What does it hurt we look at 9.* and not just just 9.1.* ? 

This change afaics just means if we have to do a 9.0.2 or 9.2.0 happens then we have to update this again.

So i'm -1 on this unless you can point to something get wrongly classified/filtered ?

**Comment by nickboldt** [comment]
Well, if 9.* is better than 9.1.*, then why do you have 8.1.* instead of 8.* ? Consistency FTW.

**Comment by maxandersen** [comment]
Looks like it was done because of the change you made to the constants.json: https://github.com/maxandersen/jiralint/commit/e00a05f262a6ef09ab8ffd69e4aab992d5621152

so yeah, I would just stay on 9.* since that requires less churn on this and does not seem to cost/hurt anything so far ?

**Comment by nickboldt** [comment]
Sure.

**Pull request closed without merging**
